### ISSUE TITLE
Color coding of nightly skypathplots

### ISSUE THREAD

**Issue by sbailey** [sbailey/surveyqa#29]
Now that PR #22 fixed the ordering of the skypathplots, the order of observations is more clear and the color coding for ordering may not be needed.  It is still hard to tell the dark vs. gray vs. bright point shapes, so let's try using colors for that instead.

i.e. let's make a branch and experiment with color coding the skypathplot points by dark/gray/bright.  Still connect them by a line, and consider drawing an extra circle or something around the first or last (not both) exposure of the night.

**Comment by rdoshi99** [comment]
A circle around the first exposure of the night clashes against the shape-coding of the different programs (Dark=hex, Gray=square, Bright=triangle) 

Possible solutions might be 
- dropping the shape coding, because the color-coding is quite distinguishing for each type of exposure program
- trying a cross or asterisk shape instead for the first exposure of the night

Attached is a screenshot below of what the color-coding and shape-coding together with asterisk of the first exposure looks like. T
he color-coding matches the darks=red/grays=blue/brights=green scheme of the summary page, but it seems to render the shape-coding unnecessary. 
Also, the current color for the first exposure is gold, because that is visible against blue, red, and green, but this can of course easily be changed for a better option.

![image](https://user-images.githubusercontent.com/46800082/54579673-cdb1ad00-49c1-11e9-9e78-02843ddb5b18.png)

**Comment by sbailey** [comment]
Color coding while dropping the shape coding is fine.  Consider making the points smaller so that they don't overlap as much.  Overlapping with the star seems to work.  Thanks for including the picture in the issue comment, that makes it much easier to understand the issues being discussed.

**Comment by sbailey** [comment]
Implemented in PR #38; closing this issue.
