### ISSUE TITLE
bokeh warnings about different column lengths

### ISSUE THREAD

**Issue by sbailey** [sbailey/surveyqa#9]
After the latest updates (I think from @williyamshoe in commit 79fa701 but I'm not entirely sure) I'm getting Bokeh warnings:
```
/Users/sbailey/anaconda3/lib/python3.6/site-packages/bokeh/models/sources.py:110: BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('date', 4093), ('x', 2), ('y', 2)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.items())), BokehUserWarning))
```
The plots still show up, albeit in a different place on the summary page than before (I preferred the old location with the progress plots at the top next to the sky plot).

Please use pull requests for future updates so that we can vet changes before they get into master rather than fixing problems after-the-fact.

**Comment by williyamshoe** [comment]
Yeah, those errors were on my part. I have fixed them and will be pushing to a new branch soon. One error, however, persists, which is:

`WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]`

I suspect that it's because I'm using dates in 2024-2025, and astropy is suspicious that these dates are incorrect. I'm not sure what to so about these errors, so I'll ignore them for the time being.

The reasoning behind putting the plots on the bottom of the page was that there was more room on the x-axis to expand out the plot, and thus to prevent the overlapping of the x-axis labels. I unfortunately cannot use a fixed x-axis tick width to solve the overcrowding issue, because the x-axis are in datetime and Bokeh uses its own autoscaling and x-axis ticks for datetimes. Now, I've tilted the labels to prevent overlapping, and put the plots back to their original location; it looks fine on my laptop, so hopefully it's fixed.

**Comment by sbailey** [comment]
ERFA warnings: indeed that is an unavoidable irritating warning from astropy, because we are trying to calculate things in the future and it can't predict the wobble of he earth's spin axis that far into the future.  For the level of precision we need that doesn't matter at all.  There are some tricks to silence that warning, but ok to ignore for now.

Thanks for working out the datetime axes.  We can continue to tweak this sort of stuff as the plots come into place.
